import "@/assets/styles/globals.css";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale} from "next-intl/server";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const locale = await getLocale();

    return (
        <html lang={locale}>
            <body className="antialiased">
                <NextIntlClientProvider>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
